### ISSUE TITLE
Can't export my journal

### ISSUE THREAD

**Issue by alienlebarge** [nathangrigg/dayone_export#23]
Hi !

I'm trying to export my journal but I get this error:

As I am a python noob, I've no idea what's the problem is.

```
Traceback (most recent call last):
  File "/usr/local/bin/dayone_export", line 9, in <module>
    load_entry_point('dayone-export==0.8.2', 'console_scripts', 'dayone_export')()
  File "/Library/Python/2.7/site-packages/dayone_export/cli.py", line 123, in run
    for filename, output in generator:
  File "/Library/Python/2.7/site-packages/dayone_export/__init__.py", line 383, in dayone_export
    yield k, template.render(journal=output_groups[k], today=today)
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/dayone_export/templates/default.html", line 51, in top-level template code
    <h1 class="entry-title">{{ entry['Date'] | format }}</h1>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 11: ordinal not in range(128)
```

It will be very nice to have some help :laughing:

Thanks

**Comment by nathangrigg** [comment]
This is now fixed in the published version. Upgrade (e.g. `pip install --upgrade dayone_export`) and try again. Thanks!
