### ISSUE TITLE
Deprecation error wrt six-1.4.1

### ISSUE THREAD

**Issue by cmcramer** [nathangrigg/dayone_export#28]
I'm not able to install with pip. I get a Deprecation notice and the install fails.

```
$ pip install dayone_export
Collecting dayone-export
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.6 in /Library/Python/2.7/site-packages (from dayone-export)
Requirement already satisfied (use --upgrade to upgrade): pytz in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from dayone-export)
Requirement already satisfied (use --upgrade to upgrade): Markdown>=2.5.1 in /Library/Python/2.7/site-packages (from dayone-export)
Collecting python-dateutil>=2.1 (from dayone-export)
  Using cached python_dateutil-2.4.2-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /Library/Python/2.7/site-packages (from Jinja2>=2.6->dayone-export)
Collecting six>=1.5 (from python-dateutil>=2.1->dayone-export)
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: six, python-dateutil, dayone-export
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 725, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 752, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 266, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/var/folders/2s/sk5tqz9s2qb2bw9g69269jm40000gn/T/pip-vzXunM-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
```

**Comment by cmcramer** [comment]
Got it installed with -
```
pip install dayone_export --ignore-installed six
```
Seems to be an El Capitan issue
https://github.com/pypa/pip/issues/3165
