### ISSUE TITLE
Traceback Error

### ISSUE THREAD

**Issue by danagerous** [nathangrigg/dayone_export#31]
Hi Nathan,

I was trying out dayone_export. I read through the documentation, followed install directions, checked installs on my machine and everything seems to be in order. Maybe I'm not using proper package version? My output below.

```
$ pip install --upgrade dayone_export
Requirement already up-to-date: dayone_export in /Library/Python/2.7/site-packages
Requirement already up-to-date: Jinja2>=2.6 in /Library/Python/2.7/site-packages (from dayone_export)
Requirement already up-to-date: pytz in /Library/Python/2.7/site-packages (from dayone_export)
Requirement already up-to-date: python-dateutil>=2.1 in /Library/Python/2.7/site-packages (from dayone_export)
Requirement already up-to-date: Markdown>=2.5.1 in /Library/Python/2.7/site-packages (from dayone_export)
Requirement already up-to-date: MarkupSafe>=0.23 in /Library/Python/2.7/site-packages (from Jinja2>=2.6->dayone_export)
Requirement already up-to-date: six>=1.5 in /Library/Python/2.7/site-packages (from python-dateutil>=2.1->dayone_export)

$ dayone_export --help
Traceback (most recent call last):
  File "/usr/local/bin/dayone_export", line 9, in <module>
    load_entry_point('dayone-export==0.8.3', 'console_scripts', 'dayone_export')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 357, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2394, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2108, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Library/Python/2.7/site-packages/dayone_export/cli.py", line 8, in <module>
    import dateutil.parser
  File "/Library/Python/2.7/site-packages/dateutil/parser.py", line 43, in <module>
    from . import tz
  File "/Library/Python/2.7/site-packages/dateutil/tz/__init__.py", line 1, in <module>
    from .tz import *
  File "/Library/Python/2.7/site-packages/dateutil/tz/tz.py", line 23, in <module>
    from ._common import tzname_in_python2, _tzinfo, _total_seconds
  File "/Library/Python/2.7/site-packages/dateutil/tz/_common.py", line 2, in <module>
    from six.moves import _thread
ImportError: cannot import name _thread
```

I'm still poking around to make sure I haven't missed something but thought I would post this anyway in case it is not me. Any help and/or direction you can provide would be appreciated.

Cheers, 
Dana

**Comment by danagerous** [comment]
Hey Nathan. I downgraded some of the packages necessary for dayone_export to work and that solved the problem.

Thanks for for your work on this app. Really appreciate it.
