### ISSUE TITLE
Traceback smart_strong

### ISSUE THREAD

**Issue by jonathan-s** [nathangrigg/dayone_export#32]
```
Traceback (most recent call last):
  File "/Users/jonathan/Dropbox/Obsidian/dayone/venv/bin/dayone_export", line 11, in <module>
    load_entry_point('dayone-export==1.0.0', 'console_scripts', 'dayone_export')()
  File "/Users/jonathan/Dropbox/Obsidian/dayone/venv/lib/python3.6/site-packages/dayone_export/cli.py", line 124, in run
    for filename, output in generator:
  File "/Users/jonathan/Dropbox/Obsidian/dayone/venv/lib/python3.6/site-packages/dayone_export/__init__.py", line 350, in dayone_export
    env.filters['markdown'] = filters.markdown_filter(autobold=autobold)
  File "/Users/jonathan/Dropbox/Obsidian/dayone/venv/lib/python3.6/site-packages/dayone_export/filters.py", line 67, in markdown_filter
    output_format='html5')
  File "/Users/jonathan/Dropbox/Obsidian/dayone/venv/lib/python3.6/site-packages/markdown/core.py", line 96, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "/Users/jonathan/Dropbox/Obsidian/dayone/venv/lib/python3.6/site-packages/markdown/core.py", line 122, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "/Users/jonathan/Dropbox/Obsidian/dayone/venv/lib/python3.6/site-packages/markdown/core.py", line 161, in build_extension
    module = importlib.import_module(ext_name)
  File "/Users/jonathan/.pyenv/versions/3.6.1/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'smart_strong'
```

**Comment by jonathan-s** [comment]
Solved with `pip install markdown==2.6.11`

**Comment by jonathan-s** [comment]
Thanks for making this btw. The export by day one into a single file was horrendous.
